permissions:
  contents: read
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
name: make
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  make:
    runs-on: ubuntu-latest
    #if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install stable
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Make
        run: make
      - name: Make install
        run: sudo make install
      - name: Check if installed
        run: command -v wait-online
      - name: Make uninstall
        run: sudo make uninstall
      - name: Check if uninstalled
        run: command -v wait-online && exit 1 || exit 0
